       </section>

    	<div class="clear"></div>
    </div>
	
    <footer>
        <!--<div class="footer-content">            
			<p>Project Created by: Kelly Nall, Chris Williams, Jessica Williams, and Elisabeth Feeley.</p>
			<p> 2013 &#169; </p>
 			<div class="clear"></div>
        </div>-->
		
        <div class="footer-bottom">
			<p>Project Created by: Kelly Nall, Chris Williams, Jessica Williams, and Elisabeth Feeley.</p>
			<p> 2013 &#169; </p>
            <p> <a href="http://zypopwebtemplates.com/">Free Website Templates</a> by ZyPOP</p>
         </div>
    </footer>
	
</div>
</body>
</html>