<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Event Media</title>
<link id="css" rel="stylesheet" href="styles.css" type="text/css" />
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<!--
brio, a free CSS web template by ZyPOP (zypopwebtemplates.com/)

Download: http://zypopwebtemplates.com/

License: Creative Commons Attribution
//-->


<!-- Something to detect mobile site -->
<script type="text/javascript">
  if (screen.width <= 800) 
  {
    document.getElementById('css').href = 'mobiles.css';
	}
</script>

</head>
<body>
<div id="container">
    <header>
    	<h1><a href="/">Event<span>Media</span></a></h1>
        <h2>We let you manage your media</h2>
    </header>
	
<nav>
    	<ul>
        	<li class=""><a href="index.php">Home</a></li>
            <li class=""><a href="examples.php">About</a></li>
			<li class=""><a href="Gallery.php">Gallery</a></li>
            <li class="end"><a href="ContactUs.php">Contact Us</a></li>
        </ul>
    </nav>
	
	<!--http://www.universityevents.harvard.edu/-->
		<img src="images/banner.jpg" alt="Event" />

	<div id="body">
		
        <section id="content">